{{- if .Values.app.hpa.frontend.enabled }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "creators-hub-app.app.projectName" . }}-frontend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "creators-hub-app.app.projectName" . }}-frontend
  minReplicas: {{ .Values.app.hpa.frontend.minReplicas }}
  maxReplicas: {{ .Values.app.hpa.frontend.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.app.hpa.frontend.averageUtilization }}
{{- end -}}
