{{- if .Values.app.hpa.backend.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "creators-hub-app.app.projectName" . }}-backend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "creators-hub-app.app.projectName" . }}-backend-nodejs
  minReplicas: {{ .Values.app.hpa.backend.minReplicas }}
  maxReplicas: {{ .Values.app.hpa.backend.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.app.hpa.backend.averageUtilization }}
{{- end -}}
