{{- if .Values.secret.enabled }}
{{- range $key, $secrets := .Values.secret.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secrets.name }}
type: {{ $secrets.type | default "Opaque" }}
{{- if $secrets.data }}
data: 
  {{- range $dkey, $dvalue := $secrets.data }}
    {{ $dkey }}: {{ $dvalue | quote }}
  {{- end }}
{{- else if $secrets.stringData }}
stringData: 
  {{- range $dkey, $dvalue := $secrets.stringData }}
    {{ $dkey }}: {{ $dvalue | quote }}
  {{- end }}
{{- end }}
---
{{- end }}
{{- end }}

{{- if .Values.app.ingress.tls.tlsCerts }}
{{- range $key, $secrets := .Values.app.ingress.tls.tlsCerts }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secrets.name }}
type: kubernetes.io/tls
data: 
  tls.crt: {{ $secrets.tlsCrt }}
  tls.key: {{ $secrets.tlsKey }}
---
{{- end }}
{{- end }}
