{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: 
      {{- include "creators-hub-app.app.serviceAccountName" . | nindent 8 }}
{{- if .Values.serviceAccount.labels }}
  labels:
  {{ toYaml .Values.serviceAccount.labels | indent 8 }}
{{- end }}
{{- if .Values.serviceAccount.annotations }}
  annotations:
    {{- range $key, $value := .Values.serviceAccount.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}  
{{- end }} 
{{- end -}}
