version: '3.4'
services:
  backend:
    image: "${DCR_HOST}/${DCR_PATH}/backend:base"
    build:
        dockerfile: deployment/Dockerfile-app-base
        context: ..
    restart: unless-stopped

  frontend:
    image: "${DCR_HOST}/${DCR_PATH}/frontend:latest"
    build:
        dockerfile: deployment/Dockerfile-nginx-base
        context: ..
    restart: unless-stopped
