FROM "${DCR_HOST}/${DCR_PATH}/backend:base" as builder
ENV NEXT_TELEMETRY_DISABLED 1
WORKDIR /app
COPY . .
RUN yarn build && yarn install --production --ignore-scripts --prefer-offline
RUN rm -f .env
RUN ls -la

FROM node:14.17-alpine AS runner
ENV NEXT_TELEMETRY_DISABLED 1
ARG NODE_ENV
ENV NODE_ENV $NODE_ENV

WORKDIR /app
RUN addgroup -g 1001 -S nodejs
RUN adduser -S nextjs -u 1001

COPY --from=builder /app/*config* ./
COPY --from=builder /app/redoc-static.html ./
COPY --from=builder /app/*.json ./
COPY --from=builder /app/next.config.js ./
RUN true
COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json


USER nextjs
EXPOSE 3000
CMD ["yarn", "start"]
